### PR TITLE
Use OASIS for building

### PR DESCRIPTION
**Pull request by toroidal-code**
Reason:
Switch to a more flexible build system that will allow for easier refactoring and modularity in the future.

Files Changed:
This commit adds an '_oasis' file, as well as associated generated files. 
It replaces the Makefile with a generated one.

Dependencies added:
Oasis (`opam install oasis`)

P.S. Sorry for doing a huge PR at once. This was the first thing I could think of contributing when I saw the project.

### CODE REVIEW

**Comment by artagnon** [comment]
First, thanks a lot for contributing! I tried building, and got:

Ocamlbuild cannot find or build librhine_stubs.ml.  A file with such a name would usually be a source file.  I suspect you have given a wrong target name to Ocamlbuild.

Maybe I'm doing something stupid, but building shouldn't be so complicated. I don't like the idea of checking in a 7k-line generated file to automatically figure out dependencies, and complicating the build process. I really liked the original Makefile: it had few moving parts and listed everything explicitly; maybe it'll become unmanageable if and when the projects grows to ~50 files, but let's talk about it then. Moreoever, contributors are more likely to be familiar with Makefiles than a system like OASIS: I don't want to make it hard to change the build system.

Let me know if I'm not thinking straight.

**Comment by toroidal-code** [comment]
Alright, that's fine.
Just wanted to try and contribute :)

**Comment by toroidal-code** [comment]
Ah, the reason the build failed was because I forgot to add a file to git that came from running `oasis setup`, you could just regenerate it. Also, you can set the `_oasis` config to generate Makefiles (like this  did) for the very reason of having a familiar build system.

**Comment by artagnon** [comment]
Thanks for the explanation; I'll probably use oasis when the project becomes larger :)

There are plenty of other contribution opportunities. If you're interested, pick up the simple task of implementing `bool?` which checks if a given argument is a boolean. See codegen.ml:230 for definitions of `int?` and others, and see toplevel.ml:135 for the `value_t` field to check. The function will be useful in coercing the first argument of an `if` to a boolean.

**Pull request closed without merging**
